package com.example.stt

/**
 * 중국어 병음(Pinyin)을 한글 발음으로 변환하는 매핑 클래스입니다.
 */
object PinyinMapper {
    val map = mapOf(
        "a" to "아", "ai" to "아이", "an" to "안", "ang" to "앙", "ao" to "아오",
        "ba" to "빠", "bai" to "바이", "ban" to "반", "bang" to "방", "bao" to "빠오",
        "bei" to "베이", "ben" to "번", "beng" to "벙", "bi" to "비", "bian" to "볜",
        "biao" to "뱌오", "bie" to "비에", "bin" to "빈", "bing" to "빙", "bo" to "뽀", "bu" to "뿌",
        "ca" to "차", "cai" to "차이", "can" to "찬", "cang" to "창", "cao" to "차오",
        "ce" to "처", "cen" to "천", "ceng" to "청", "cha" to "차", "chai" to "차이",
        "chan" to "찬", "chang" to "창", "chao" to "차오", "che" to "처", "chen" to "천",
        "cheng" to "청", "chi" to "치", "chong" to "충", "chou" to "처우", "chu" to "추",
        "chua" to "추아", "chuai" to "추아이", "chuan" to "추안", "chuang" to "창",
        "chui" to "추이", "chun" to "춘", "chuo" to "추어", "ci" to "츠", "cong" to "총",
        "cou" to "처우", "cu" to "추", "cuan" to "추안", "cui" to "추이", "cun" to "춘",
        "cuo" to "추어", "da" to "따", "dai" to "따이", "dan" to "딴", "dang" to "땅",
        "dao" to "따오", "de" to "더", "dei" to "데이", "den" to "던", "deng" to "떵",
        "di" to "띠", "dian" to "뗸", "diao" to "땨오", "die" to "띠에", "ding" to "띵",
        "diu" to "띠우", "dong" to "뚱", "dou" to "떠우", "du" to "뚜", "duan" to "똰",
        "dui" to "뚜이", "dun" to "뚠", "duo" to "뚜어", "e" to "으어", "ei" to "에이",
        "en" to "언", "eng" to "엉", "er" to "얼", "fa" to "파", "fan" to "판",
        "fang" to "팡", "fei" to "페이", "fen" to "펀", "feng" to "펑", "fo" to "포",
        "fou" to "퍼우", "fu" to "푸", "ga" to "까", "gai" to "까이", "gan" to "깐",
        "gang" to "깡", "gao" to "까오", "ge" to "끄어", "gei" to "게이", "gen" to "껀",
        "geng" to "껑", "gong" to "꿍", "gou" to "꺼우", "gu" to "꾸", "gua" to "꽈",
        "guai" to "꽈이", "guan" to "꽌", "guang" to "꽝", "gui" to "꾸이", "gun" to "꾼",
        "guo" to "꾸어", "ha" to "하", "hai" to "하이", "han" to "한", "hang" to "항",
        "hao" to "하오", "he" to "허", "hei" to "헤이", "hen" to "헌", "heng" to "헝",
        "hong" to "훙", "hou" to "허우", "hu" to "후", "hua" to "화", "huai" to "화이",
        "huan" to "환", "huang" to "황", "hui" to "후이", "hun" to "훈", "huo" to "후어",
        "ji" to "지", "jia" to "쟈", "jian" to "졘", "jiang" to "쟝", "jiao" to "쟈오",
        "jie" to "지에", "jin" to "진", "jing" to "징", "jiong" to "중", "jiu" to "지우",
        "ju" to "쥐", "juan" to "쥐안", "jue" to "쥐에", "jun" to "쥔", "ka" to "카",
        "kai" to "카이", "kan" to "칸", "kang" to "캉", "kao" to "카오", "ke" to "커",
        "kei" to "케이", "ken" to "컨", "keng" to "컹", "kong" to "쿵", "kou" to "커우",
        "ku" to "쿠", "kua" to "콰", "kuai" to "콰이", "kuan" to "콴", "kuang" to "쾅",
        "kui" to "쿠이", "kun" to "쿤", "kuo" to "쿠어", "la" to "라", "lai" to "라이",
        "lan" to "란", "lang" to "랑", "lao" to "라오", "le" to "러", "lei" to "레이",
        "leng" to "렁", "li" to "리", "lia" to "랴", "lian" to "롄", "liang" to "량",
        "liao" to "랴오", "lie" to "리에", "lin" to "린", "ling" to "링", "liu" to "리우",
        "long" to "룽", "lou" to "러우", "lu" to "루", "lv" to "뤼", "luan" to "롼",
        "lue" to "뤼에", "lun" to "룬", "luo" to "루어", "ma" to "마", "mai" to "마이",
        "man" to "만", "mang" to "망", "mao" to "마오", "me" to "머", "mei" to "메이",
        "men" to "먼", "meng" to "멍", "mi" to "미", "mian" to "몐", "miao" to "먀오",
        "mie" to "미에", "min" to "민", "ming" to "밍", "miu" to "미우", "mo" to "모",
        "mou" to "머우", "mu" to "무", "na" to "나", "nai" to "나이", "nan" to "난",
        "nang" to "낭", "nao" to "나오", "ne" to "너", "nei" to "네이", "nen" to "넌",
        "neng" to "넝", "ni" to "니", "nia" to "냐", "nian" to "녠", "niang" to "냥",
        "niao" to "냐오", "nie" to "니에", "nin" to "닌", "ning" to "닝", "niu" to "니우",
        "nong" to "눙", "nou" to "너우", "nu" to "누", "nv" to "뉘", "nuan" to "놘",
        "nue" to "뉘에", "nun" to "눈", "nuo" to "누어", "o" to "오", "ou" to "어우",
        "pa" to "파", "pai" to "파이", "pan" to "판", "pang" to "팡", "pao" to "파오",
        "pei" to "페이", "pen" to "펀", "peng" to "펑", "pi" to "피", "pian" to "폔",
        "piao" to "표", "pie" to "피에", "pin" to "핀", "ping" to "핑", "po" to "포",
        "pou" to "퍼우", "pu" to "푸", "qi" to "치", "qia" to "챠", "qian" to "쳰",
        "qiang" to "챵", "qiao" to "챠오", "qie" to "치에", "qin" to "친", "qing" to "칭",
        "qiong" to "충", "qiu" to "치우", "qu" to "취", "quan" to "취안", "que" to "취에",
        "qun" to "췬", "ran" to "란", "rang" to "랑", "rao" to "라오", "re" to "러",
        "ren" to "런", "reng" to "렁", "ri" to "르", "rong" to "룽", "rou" to "러우",
        "ru" to "루", "ruan" to "롼", "rui" to "루이", "run" to "룬", "ruo" to "루어",
        "sa" to "싸", "sai" to "싸이", "san" to "싼", "sang" to "쌍", "sao" to "싸오",
        "se" to "쓰어", "sen" to "썬", "seng" to "썽", "sha" to "샤", "shai" to "샤이",
        "shan" to "샨", "shang" to "샹", "shao" to "샤오", "she" to "셔", "shei" to "셰이",
        "shen" to "션", "sheng" to "셩", "shi" to "스", "shou" to "셔우", "shu" to "슈",
        "shua" to "솨", "shuai" to "솨이", "shuan" to "솬", "shuang" to "솽", "shui" to "수이",
        "shun" to "순", "shuo" to "슈어", "si" to "쓰", "song" to "쑹", "sou" to "써우",
        "su" to "쑤", "suan" to "쏸", "sui" to "쑤이", "sun" to "쑨", "suo" to "쑤어",
        "ta" to "타", "tai" to "타이", "tan" to "탄", "tang" to "탕", "tao" to "타오",
        "te" to "터", "teng" to "텅", "ti" to "티", "tian" to "톈", "tiao" to "탸오",
        "tie" to "티에", "ting" to "팅", "tong" to "퉁", "tou" to "터우", "tu" to "투",
        "tuan" to "퉌", "tui" to "투이", "tun" to "툰", "tuo" to "투어", "wa" to "와",
        "wai" to "와이", "wan" to "완", "wang" to "왕", "wei" to "웨이", "wen" to "원",
        "weng" to "웡", "wo" to "워", "wu" to "우", "xi" to "시", "xia" to "샤",
        "xian" to "셴", "xiang" to "샹", "xiao" to "샤오", "xie" to "시에", "xin" to "신",
        "xing" to "싱", "xiong" to "슝", "xiu" to "시우", "xu" to "쉬", "xuan" to "쉬안",
        "xue" to "쉬에", "xun" to "쉰", "ya" to "야", "yan" to "옌", "yang" to "양",
        "yao" to "야오", "ye" to "예", "yi" to "이", "yin" to "인", "ying" to "잉",
        "yo" to "요", "yong" to "융", "you" to "유", "yu" to "위", "yuan" to "위안",
        "yue" to "위에", "yun" to "윈", "za" to "짜", "zai" to "짜이", "zan" to "짠",
        "zang" to "짱", "zao" to "짜오", "ze" to "쯔어", "zei" to "제이", "zen" to "쩐",
        "zeng" to "쩡", "zha" to "자", "zhai" to "자이", "zhan" to "잔", "zhang" to "장",
        "zhao" to "자오", "zhe" to "저", "zhen" to "전", "zheng" to "정", "zhi" to "즈",
        "zhong" to "중", "zhou" to "저우", "zhu" to "주", "zhua" to "주아", "zhuai" to "주아이",
        "zhuan" to "좐", "zhuang" to "좡", "zhui" to "주이", "zhun" to "준", "zhuo" to "주어",
        "zi" to "쯔", "zong" to "쭝", "zou" to "쩌우", "zu" to "쭈", "zuan" to "쫘",
        "zui" to "쭈이", "zun" to "쭌", "zuo" to "쭈어"
    )
}
